TAG: main
CONFIG_REPO:
TOKEN:

- name: Install Phoenix CTMS
  hosts: all
  remote_user: root
  become: true
  vars:
    xms: "2048m"
    xmx: "4096m"
    xss: "512k"
    perm: "256m"
    tomcat_major_version: 9
    tomcat_permissions_production: False
    tomcat_users:
      - username: "ctsms"
        password: "ctsms"
        roles: "tomcat,admin,manager,manager-gui"
  roles:
    - java-open-jdk11
    - vantaworks.tomcat

  tasks:
  - name: Install General Packages
    apt:
      pkg:
        - sudo
        - wget
        - curl
        - lsb-release
        - gnupg
        - ntpd
      state: latest
      update_cache: true

  - name: Sync Time
    service: name=ntp state=started enabled=yes

  - name: Create 'ctsms' user
    ansible.builtin.user:
      name: ctsms
      shell: /bin/bash

  - name: Prepare /ctsms directory with default-config and master-data
    ansible.builtin.file:
      path: /ctsms
      state: directory
