- name: Install Phoenix CTMS v1.8.2
  gather_facts: false
  hosts: all
  tasks:
  - name: Install General Packages
    hosts: all
    apt:
      pkg:
        - sudo
        - wget
        - curl
        - lsb-release
        - gnupg
        - ntpd
      state: latest
      update_cache: true

  - name: Sync Time
    hosts: all
    ansible.builtin.service:
      name: ntp
      state: started
      enabled=: yes

  - name: Create 'ctsms' user
    hosts: all
    ansible.builtin.user:
      name: ctsms

  - name: Prepare ctsms directory with default-config and master-data
    hosts: all
    ansible.builtin.import_playbook: playbooks/prepare-ctsms-directory.yml

  - name: Install OpenJDK
    hosts: all
    ansible.builtin.apt:
      - openjdk

  - name: Install tomcat9
    hosts: webapp
    ansible.builtin.import_playbook: playbooks/tomcat9.yml

  - name: Build phoenix
    hosts: webapp
    ansible.builtin.import_playbook: playbooks/build-phoenix.yml

  - name: Install Postgres 13
    hosts: db
    ansible.builtin.import_playbook: playbooks/install-postgres.yml

  - name: Enable SSH and database remote access
    hosts: db
    ansible.builtin.import_playbook: playbooks/enable-remote-access.yml

  - name: deploy .war
    hosts: webapp
    ansible.builtin.import_playbook: playbooks/deploy-war.yml

  - name: install memcached
    hosts: bulk-processor
    ansible.builtin.import_playbook: playbooks/install-memcached.yml

  - name: install bulk_processor
    hosts: bulk-processor
    ansible.builtin.import_playbook: playbooks/install-bulk-processor.yml

  - name: setup apache2
    hosts: reverse-proxy
    ansible.builtin.import_playbook: playbooks/setup-apache2.yml

  # - name: initialize database

  - name: install cron
    hosts: webapp
    ansible.builtin.import_playbook: playbooks/install-cron.yml

  - name: Setup logrotate
    hosts: webapp
    ansible.builtin.template:
      src: ./templates/logrotate/ctsms.j2
      dest: /etc/logrotate.d/ctsms
      owner: root
      group: wheel
      mode: "0644"

  - name: render workflow diagrams
    hosts: webapp
    ansible.builtin.import_playbook: playbooks/render-workflow-diagrams.yml
  #
  - name: ready
    hosts: all
    ansible.builtin.debug:
      msg: Phoenix CTMS installation finished.
