- name: Install Phoenix CTMS v1.8.2
  gather_facts: false
  hosts: all
  tasks:
  - name: Install General Packages
    hosts: all
    apt:
      pkg:
        - sudo
        - wget
        - curl
        - lsb-release
        - gnupg
        - ntpd
      state: latest
      update_cache: true

  - name: Sync Time
    hosts: all
    service: name=ntp state=started enabled=yes

  - name: Create 'ctsms' user
    hosts: all
    ansible.builtin.user:
      name: ctsms

  - name: Prepare ctsms directory with default-config and master-data
    hosts: all
    ansible.builtin.import_playbook: playbooks/prepare-ctsms-directory.yml

  - name: Install OpenJDK
    ansible.builtin.apt:
      - openjdk

  - name: Install tomcat9
    hosts: all
    ansible.builtin.import_playbook: playbooks/tomcat9.yml

  - name: Build phoenix
    hosts: all
    ansible.builtin.import_playbook: playbooks/build-phoenix.yml

  # - name: Install Postgres 13
  #
  # - name: Enable SSH and database remote access
  #
  # - name: deploy .war
  #
  # - name: install bulk_processor
  #
  # - name: setup apache2
  # - name: initialize database
  # - name: setup cron
  # - name: setup logrotate
  # - name: render workflow diagrams
  #
  # - name: ready
