- name: Build Phoenix CTMS
  become: true
  hosts: all
  tasks:
    - name: install maven
      ansible.builtin.apt:
        name: maven
        state: present

    - name: Remove /ctsms/build
      ansible.builtin.file:
        path: /ctsms/build
        state: absent

    - name: Create /ctsms/build
      ansible.builtin.file:
        path: /ctsms/build
        state: directory

    - name: Clone Phoenix repository
      ansible.builtin.git:
        repo: 'https://github.com/phoenixctms/ctsms.git'
        dest: /ctsms/build/

    - name: Read application.version from pom.xml
      command: grep -oP '<application.version>\K[^<]+' /ctsms/build/ctsms/pom.xml
      register: app_version

    - name: Get short git commit hash
      command: git rev-parse --short HEAD
      args:
        chdir: /ctsms/build/ctsms
      register: git_commit

    - name: Generate a UUID
      command: cat /proc/sys/kernel/random/uuid
      register: uuid_output

    - name: Update application.version in pom.xml with commit hash
      replace:
        path: /ctsms/build/ctsms/pom.xml
        regexp: '(<application.version>)[^<]+(</application.version>)'
        replace: '\1{{ app_version.stdout }} [{{ git_commit.stdout }}]\2'

    - name: Update application.uuid tag with generated UUID
      replace:
        path: /ctsms/build/ctsms/pom.xml
        regexp: '<application\.uuid></application\.uuid>'
        replace: '<application.uuid>{{ uuid_output.stdout }}</application.uuid>'

    - name: Run mvn install with -DskipTests
      command: mvn install -DskipTests
      args:
        chdir: /ctsms/build/ctsms
      register: mvn_install
      changed_when: "'BUILD SUCCESS' in mvn_install.stdout"

    - name: Check if .war file exists
      stat:
        path: "/ctsms/build/ctsms/web/target/ctsms-{{ app_version.stdout }}.war"
      register: war_file

    - name: Retry mvn install if .war file was not created
      command: mvn install -DskipTests
      args:
        chdir: /ctsms/build/ctsms
      when: not war_file.stat.exists
      register: mvn_retry
      changed_when: "'BUILD SUCCESS' in mvn_retry.stdout"

    - name: Run andromdapp-maven-plugin (create schema)
      command: >
        mvn -f core/pom.xml org.andromda.maven.plugins:andromdapp-maven-plugin:schema -Dtasks=create
      args:
        chdir: /ctsms/build/ctsms

    - name: Run andromdapp-maven-plugin (drop schema)
      command: >
        mvn -f core/pom.xml org.andromda.maven.plugins:andromdapp-maven-plugin:schema -Dtasks=drop
      args:
        chdir: /ctsms/build/ctsms
