- name: Deploy .war
  become: true
  tasks:
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /ctsms/build/ctsms/web/target/ctsms-{{ version }}.war
        mode: '0755'

    - name: Remove /ctsms/bulk_processor
      ansible.builtin.file:
        path: /var/lib/tomcat9/webapps/ROOT/
        state: absent

    - name: Copy .war to Tomcat directory
      ansible.builtin.copy:
        src: /ctsms/build/ctsms/web/target/ctsms-{{ version }}.war
        dest: /var/lib/tomcat9/webapps/ROOT.war
        mode: '0755'
