- name: Install bulk-processor
  connection: local
  become: true
  vars:
    tag: "master"
    base_url: "https://github.com/phoenixctms"
    bulk_processor_url: "{{ base_url }}/bulk-processor/archive/{{ tag }}.tar.gz"
    scripts_base_url: "{{ base_url }}/install-debian/{{ tag }}"
    dest_dir: "/ctsms/bulk_processor"
    output_dir: "{{ dest_dir }}/output"
    user_group: "ctsms"
  tasks:
    - name: Install Perl libraries and utilities
      ansible.builtin.apt:
        name:
          - libarchive-zip-perl
          - libconfig-any-perl
          - libdata-dump-perl
          - libdata-dumper-concise-perl
          - libdata-uuid-perl
          - libdata-validate-ip-perl
          - libdate-calc-perl
          - libdate-manip-perl
          - libdatetime-format-iso8601-perl
          - libdatetime-format-strptime-perl
          - libdatetime-perl
          - libdatetime-timezone-perl
          - libdbd-csv-perl
          - libdbd-mysql-perl
          - libdbd-sqlite3-perl
          - tdsodbc
          - libdbd-odbc-perl
          - libdigest-md5-perl
          - libemail-mime-attachment-stripper-perl
          - libemail-mime-perl
          - libgearman-client-perl
          - libhtml-parser-perl
          - libintl-perl
          - libio-compress-perl
          - libio-socket-ssl-perl
          - libjson-xs-perl
          - liblog-log4perl-perl
          - libmail-imapclient-perl
          - libmarpa-r2-perl
          - libmime-base64-perl
          - libmime-lite-perl
          - libmime-tools-perl
          - libnet-address-ip-local-perl
          - libnet-smtp-ssl-perl
          - libole-storage-lite-perl
          - libphp-serialization-perl
          - libexcel-writer-xlsx-perl
          - libspreadsheet-parseexcel-perl
          - libstring-mkpasswd-perl
          - libtext-csv-xs-perl
          - libtie-ixhash-perl
          - libtime-warp-perl
          - liburi-find-perl
          - libuuid-perl
          - libwww-perl
          - libxml-dumper-perl
          - libxml-libxml-perl
          - libyaml-libyaml-perl
          - libyaml-tiny-perl
          - libtemplate-perl
          - libdancer-perl
          - libdbd-pg-perl
          - libredis-perl
          - libjson-perl
          - libplack-perl
          - libcache-memcached-perl
          - libdancer-session-memcached-perl
          - libgraphviz-perl
          - gnuplot
          - imagemagick
          - ghostscript
          - build-essential
          - libtest-utf8-perl
          - libmoosex-hasdefaults-perl
          - cpanminus
        state: present
        update_cache: yes
        force: yes

    - name: replace in sql files
      shell: sed -r -i 's/^\s*(<policy domain="coder" rights="none" pattern="PS" \/>)\s*$/<!--\1-->/' /etc/ImageMagick-6/policy.xml

    - name: Install libsys-cpuaffinity-perl (Debian)
      ansible.builtin.apt:
        name:
          - libsys-cpuaffinity-perl
        state: present
        update_cache: yes
        force: yes
      when: ansible_os_family == "Debian"

    - name: Install Perl CPU Affinity
      community.general.cpanm:
        name:
          - Sys
          - threads
      when: ansible_os_family != "Debian"

    - name: Install Perl modules
      community.general.cpanm:
        name:
          - Dancer
          - DateTime::Format::Excel
          - Spreadsheet::Reader::Format
          - Spreadsheet::Reader::ExcelXML
        mode: compatibility
