- name: Install bulk-processor
  become: true
  hosts: all
  vars:
    tag: "master"
    base_url: "https://github.com/phoenixctms"
    bulk_processor_url: "{{ base_url }}/bulk-processor/archive/{{ tag }}.tar.gz"
    scripts_base_url: "{{ base_url }}/install-debian/{{ tag }}"
    dest_dir: "/ctsms/bulk_processor"
    output_dir: "{{ dest_dir }}/output"
    user_group: "ctsms"
  hosts: all
  tasks:
    - name: Install Perl libraries and utilities
      ansible.builtin.apt:
        name:
          - libarchive-zip-perl
          - libconfig-any-perl
          - libdata-dump-perl
          - libdata-dumper-concise-perl
          - libdata-uuid-perl
          - libdata-validate-ip-perl
          - libdate-calc-perl
          - libdate-manip-perl
          - libdatetime-format-iso8601-perl
          - libdatetime-format-strptime-perl
          - libdatetime-perl
          - libdatetime-timezone-perl
          - libdbd-csv-perl
          - libdbd-mysql-perl
          - libdbd-sqlite3-perl
          - tdsodbc
          - libdbd-odbc-perl
          - libdigest-md5-perl
          - libemail-mime-attachment-stripper-perl
          - libemail-mime-perl
          - libgearman-client-perl
          - libhtml-parser-perl
          - libintl-perl
          - libio-compress-perl
          - libio-socket-ssl-perl
          - libjson-xs-perl
          - liblog-log4perl-perl
          - libmail-imapclient-perl
          - libmarpa-r2-perl
          - libmime-base64-perl
          - libmime-lite-perl
          - libmime-tools-perl
          - libnet-address-ip-local-perl
          - libnet-smtp-ssl-perl
          - libole-storage-lite-perl
          - libphp-serialization-perl
          - libexcel-writer-xlsx-perl
          - libspreadsheet-parseexcel-perl
          - libstring-mkpasswd-perl
          - libtext-csv-xs-perl
          - libtie-ixhash-perl
          - libtime-warp-perl
          - liburi-find-perl
          - libuuid-perl
          - libwww-perl
          - libxml-dumper-perl
          - libxml-libxml-perl
          - libyaml-libyaml-perl
          - libyaml-tiny-perl
          - libtemplate-perl
          - libdancer-perl
          - libdbd-pg-perl
          - libredis-perl
          - libjson-perl
          - libplack-perl
          - libcache-memcached-perl
          - libdancer-session-memcached-perl
          - libgraphviz-perl
          - gnuplot
          - imagemagick
          - ghostscript
          - build-essential
          - libtest-utf8-perl
          - libmoosex-hasdefaults-perl
          - cpanminus
        state: present
        update_cache: yes
        force: yes

    - name: Comment out PS policy line in ImageMagick policy.xml
      replace:
        path: /etc/ImageMagick-6/policy.xml
        regexp: '^\s*(<policy domain="coder" rights="none" pattern="PS" \/>)(\s*)$'
        replace: '<!--\1-->'
        backup: yes

    - name: Install libsys-cpuaffinity-perl (Debian)
      ansible.builtin.apt:
        name:
          - libsys-cpuaffinity-perl
        state: present
        update_cache: yes
        force: yes
      when: ansible_os_family == "Debian"

    - name: Install sys, threads from CPANM
      community.general.cpanm:
        name:
          - Sys
          - threads
      when: ansible_os_family != "Debian"

    - name: Install Dancer module from CPANM
      community.general.cpanm:
        name: Dancer
        mode: compatibility

    - name: Install DateTime module from CPANM
      community.general.cpanm:
        name: DateTime::Format::Excel
        mode: compatibility

    - name: Install Spreadsheet::Reader::Format module from CPANM
      community.general.cpanm:
        name: Spreadsheet::Reader::Format
        mode: compatibility

    - name: Install Spreadsheet::Reader::ExcelXML module from CPANM
      community.general.cpanm:
        name: Spreadsheet::Reader::ExcelXML
        mode: compatibility

    - name: Download bulk-processor archive
      ansible.builtin.get_url:
        url: "https://github.com/phoenixctms/bulk-processor/archive/{{ tag }}.tar.gz"
        dest: /ctsms/bulk-processor.tar.gz
        mode: '0644'
        force: true
        validate_certs: false
        headers:
          Content-Disposition: "attachment"

    - name: Create /ctsms/bulk_processor
      ansible.builtin.file:
        path: /ctsms/bulk_processor
        state: directory

    - name: Extract bulk-processor archive
      ansible.builtin.unarchive:
        src: /ctsms/bulk-processor.tar.gz
        dest: /ctsms/bulk_processor
        remote_src: true
        extra_opts:
          - --strip-components=1

    - name: Run minify.pl on Signup folder
      cmd: perl /ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/WebApps/minify.pl --folder=/ctsms/bulk_processor/CTSMS/BulkProcessor/Projects/WebApps/Signup

    - name: Create /ctsms/bulk_processor/output directory
      ansible.builtin.file:
        path: /ctsms/bulk_processor/output
        state: directory
        mode: '0777'
        recurse: true
        owner: ctsms
        group: ctsms

    - name: Ensure ownership of /ctsms/bulk_processor
      ansible.builtin.file:
        path: /ctsms/bulk_processor
        state: directory
        recurse: true
        owner: ctsms
        group: ctsms

    - name: Set permissions 0755 on /ctsms/bulk_processor
      ansible.builtin.file:
        path: /ctsms/bulk_processor
        state: directory
        recurse: true
        mode: '0755'

    - name: Set permissions 0777 on /ctsms/bulk_processor/output
      ansible.builtin.file:
        path: /ctsms/bulk_processor/output
        state: directory
        recurse: true
        mode: '0777'

    - name: Remove archive file /ctsms/bulk-processor.tar.gz
      ansible.builtin.file:
        path: /ctsms/bulk-processor.tar.gz
        state: absent

    - name: Template ecrfdataexport.sh to /ctsms/
      ansible.builtin.template:
        src: ../templates/shell/ecrfdataexport.j2
        dest: /ctsms/ecrfdataexport.sh
        owner: ctsms
        group: ctsms
        mode: '0755'

    - name: Template ecrfdataeimport.sh to /ctsms/
      ansible.builtin.template:
        src: ../templates/shell/ecrfdataimport.j2
        dest: /ctsms/ecrfdataimport.sh
        owner: ctsms
        group: ctsms
        mode: '0755'

    - name: Template inquirydataexport.sh to /ctsms/
      ansible.builtin.template:
        src: ../templates/shell/inquirydataexport.j2
        dest: /ctsms/inquirydataexport.sh
        owner: ctsms
        group: ctsms
        mode: '0755'
