- name: Prepare CTMS directory
  gather_facts: true
  hosts: all
  become: true
  vars:
    xms: "2048m"
    xmx: "4096m"
    xss: "512k"
    perm: "256m"
  tasks:
    - name: Create /ctsms
      ansible.builtin.file:
        path: /ctsms/
        state: directory
        mode: '0755'

    - name: Remove /ctsms/bulk_processor
      ansible.builtin.file:
        path: /ctsms/bulk_processor/
        state: absent

    - name: Write dbtool.sh
      ansible.builtin.copy:
        dest: /ctsms.dbtool.sh
        content: |
          #!/bin/bash
          CTSMS_PROPERTIES=${CTSMS_PROPERTIES:-/ctsms/properties}
          CTSMS_JAVA=${CTSMS_JAVA:-/ctsms/java}
          CATALINA_BASE=${CATALINA_BASE:-/var/lib/tomcat9}
          java -DCTSMS_PROPERTIES="$CTSMS_PROPERTIES" -DCTSMS_JAVA="$CTSMS_JAVA" -Dfile.encoding=Cp1252 -Djava.awt.headless=true --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED -Xms{{ ansible_facts['xms'] }} -Xmx{{ ansible_facts['xmx'] }} -Xss{{ ansible_facts['xss'] }} -XX:+UseParallelGC -XX:MaxGCPauseMillis=1500 -XX:GCTimeRatio=9 -XX:+CMSClassUnloadingEnabled -XX:ReservedCodeCacheSize={{ ansible_facts['perm'] }} -classpath $CATALINA_BASE/webapps/ROOT/WEB-INF/lib/ctsms-core-1.8.1.jar:$CATALINA_BASE/webapps/ROOT/WEB-INF/lib/* org.phoenixctms.ctsms.executable.DBTool $*

    - name: Template clearcache to /ctsms/clearcache.sh
      ansible.builtin.template:
        src:  ../templates/shell/clearcache.sh.j2
        dest: /ctsms/clearcache.sh
        owner: ctsms
        group: ctsms
        mode: '0755'

    - name: Copy config-default to /ctsms/config-default/
      ansible.builtin.copy:
        src: ../config-default/
        dest: /ctsms/config-default/
        owner: ctsms
        group: ctsms
        mode: '0755'

    - name: Template dbtool to /ctsms/dbtool.sh
      ansible.builtin.template:
        src: ../templates/shell/dbtool.sh.j2
        dest: /ctsms/dbtool.sh
        owner: ctsms
        group: ctsms
        mode: '0755'

    - name: Copy master-data to /ctsms/master_data/
      ansible.builtin.copy:
        src: ../master-data/
        dest: /ctsms/master_data/
        owner: ctsms
        group: ctsms
        mode: '0755'

    - name: Recursively change ownership of /ctsms/
      ansible.builtin.file:
        path: /ctsms/
        state: directory
        recurse: yes
        owner: ctsms
        group: ctsms
        mode: '0755'

    - name: Recursively change ownership of /ctsms/external_files
      ansible.builtin.file:
        path: /ctsms/external_files
        state: directory
        recurse: yes
        owner: ctsms
        group: ctsms
        mode: '0755'

    - name: Template update to /ctsms/update
      ansible.builtin.template:
        src: ../templates/update.j2
        dest: /ctsms/update.sh
        owner: ctsms
        group: ctsms
        mode: '0755'
