tasks:
  - name: Create /ctsms
    ansible.builtin.file:
      path: /ctsms/
      state: directory
      mode: '0755'

  - name: Remove /ctsms/bulk_processor
    ansible.builtin.file:
      path: /ctsms/bulk_processor/
      state: absent

  - name: Template dbtool to /ctsms/dbtool.sh
    ansible.builtin.template:
      src: ./templates/dbtool.sh.j2
      dest: /ctsms/dbtool.sh
      owner: ctsms
      group: ctsms
      mode: '0755'

  - name: Template clearcache to /ctsms/clearcache.sh
    ansible.builtin.template:
      src: ./templates/bash/clearcache.sh.j2
      dest: /ctsms/clearcache.sh
      owner: ctsms
      group: ctsms
      mode: '0755'

  - name: Copy config-default to /ctsms/config-default/
    ansible.builtin.copy:
      src: ./master-data/
      dest: /ctsms/config-default/
      owner: ctsms
      group: ctsms
      mode: '0755'

  - name: Template dbtool to /ctsms/dbtool.sh
    ansible.builtin.template:
      src: ./templates/bash/dbtool.sh.j2
      dest: /ctsms/dbtool.sh
      owner: ctsms
      group: ctsms
      mode: '0755'

  - name: Copy master-data to /ctsms/master_data/
    ansible.builtin.copy:
      src: ./master-data/
      dest: /ctsms/master_data/
      owner: ctsms
      group: ctsms
      mode: '0755'

  - name: Recursively change ownership of /ctsms/
    ansible.builtin.file:
      path: /ctsms/
      state: directory
      recurse: yes
      owner: ctsms
      group: ctsms
      mode: '0755'

  - name: Recursively change ownership of /ctsms/external_files
    ansible.builtin.file:
      path: /ctsms/external_files
      state: directory
      recurse: yes
      owner: ctsms
      group: ctsms
      mode: '0755'

  - name: Template update to /ctsms/update
    ansible.builtin.template:
      src: ./templates/update.j2
      dest: /ctsms/update.sh
      owner: ctsms
      group: ctsms
      mode: '0755'
