- name: Install Apache2
  become: true
  vars:
    certificate: "self-signed"
    organization: "Phoenix CTMS"
  hosts: all
  tasks:
    - name: Install Apache and required modules
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-jk
          - libapache2-mod-fcgid
        state: present
        update_cache: true
      notify: Reload Apache

    - name: Run usermod
      ansible.builtin.command: usermod --append --groups tomcat,ctsms www-data

    - name: Template 00_ctsms_http.conf to /etc/apache2/sites-available/
      ansible.builtin.template:
        src: ../templates/apache/00_ctsms_http.conf.j2
        dest: /etc/apache2/sites-available/00_ctsms_http.conf
      notify: Reload Apache

    - name: Template 00_ctsms_https.conf to /etc/apache2/sites-available/
      ansible.builtin.template:
        src: ../templates/apache/00_ctsms_https.conf.j2
        dest: /etc/apache2/sites-available/00_ctsms_https.conf
      notify: Reload Apache

    - name: Template blocklist.conf to /etc/apache2/
      ansible.builtin.template:
        src: ../templates/apache/blocklist.conf.j2
        dest: /etc/apache2/blocklist.conf
      notify: Reload Apache

    - name: Template jk.conf to /etc/apache2/mods-available/
      ansible.builtin.template:
        src: ../templates/apache/jk.conf.j2
        dest: /etc/apache2/mods-available/
      notify: Reload Apache

    - name: Disable default Apache site
      ansible.builtin.command: a2dissite 000-default.conf
      notify: Reload Apache

    - name: Enable 00_ctsms_http.conf site
      ansible.builtin.command: a2ensite 00_ctsms_http.conf
      notify: Reload Apache

    - name: Enable Apache SSL module
      ansible.builtin.command: a2enmod ssl
      notify: Reload Apache

    - name: Enable Apache rewrite module
      ansible.builtin.command: a2enmod rewrite
      notify: Reload Apache

    - name: Create SSL directory
      ansible.builtin.file:
        path: /etc/apache2/ssl
        state: directory
        mode: '0600'
        owner: root
        group: root

    - name: Create private key (RSA, 4096 bits)
      community.crypto.openssl_privatekey:
        path: /etc/apache2/ssl/apache.key

    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: /etc/apache2/ssl/apache.key
        common_name: "{{ ansible_hostname }}"
        organization_name: "{{ organization }}"
        subject_alt_name:
          - "DNS:ansible.com"
          - "DNS:www.ansible.com"
          - "DNS:docs.ansible.com"
      register: csr

    - name: Create self-signed certificate from CSR
      community.crypto.x509_certificate:
        path: /etc/apache2/ssl/certificate.pem
        csr_content: "{{ csr.csr }}"
        privatekey_path: /etc/apache2/ssl/apache.key
        provider: selfsigned

    - name: Enable 00_ctsms_https.conf site
      ansible.builtin.command: a2ensite 00_ctsms_https.conf
      notify: Reload Apache

  handlers:
    - name: Reload Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
